# Lab 1 – Basic NumPy Operations

## Introduction

This lab demonstrates basic NumPy operations including array creation, indexing, slicing, reshaping, stacking, splitting, broadcasting, matrix multiplication and solving systems of linear equations.

In [29]:
import numpy as np

Part - A

A2. Array from 1 to 20

The `np.arange()` function is used to create an array with values starting from 1 and increasing by 2. The sequence continues until it reaches a value less than or equal to 20.

In [30]:
ar = np.arange(1, 21, 2)

print("Array:", ar)

Array: [ 1  3  5  7  9 11 13 15 17 19]


 A3. Random Array

 The `np.random.rand()` function is used to generate random numbers between 0 and 1. In this example, an array containing three random values is created. The `shape` attribute is used to display the shape of the array.

In [31]:
random_array = np.random.rand(3)

print("Random array:", random_array)
print("Shape:", random_array.shape)

Random array: [0.8154783  0.8431302  0.24437903]
Shape: (3,)


 A4. 2-D Array and Slicing

A 2-D NumPy array is created using the given values. Array slicing is then used to select specific rows. The first two rows are selected using `[:1]`, while the last two rows are selected using `[-1:]`.

In [32]:
array_2d = np.array([
    [10, 20, 45],
    [30, 12, 16],
    [42, 17, 56]
])

print("2-D Array:")
print(array_2d)

print("\nFirst one rows:")
print(array_2d[:1])

print("\nLast one rows:")
print(array_2d[-1:])

2-D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First one rows:
[[10 20 45]]

Last one rows:
[[42 17 56]]


A5. Stacking and Splitting

Two 2 × 2 arrays are created and combined using NumPy stacking operations. `np.vstack()` combines the arrays vertically, while `np.hstack()` combines them horizontally. The `np.vsplit()` function is used to divide the combined array into smaller arrays.

In [33]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A:")
print(A)

print("\nB:")
print(B)

print("\nVertical Stack:")
print(np.vstack((A, B)))

print("\nHorizontal Stack:")
print(np.hstack((A, B)))

print("\nSplit:")
for part in np.vsplit(np.vstack((A, B)), 2):
    print(part)

A:
[[1 2]
 [3 4]]

B:
[[5 6]
 [7 8]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]

Split:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


A6. Matrix Multiplication


Matrix multiplication is possible when the number of columns in the first matrix equals the number of rows in the second matrix. X has shape (3,3) and Y has shape (3,2), so the multiplication is possible.

In [34]:
X = np.array([
    [5, 7, 2],
    [4, 5, 6],
    [7, 4, 1]
])

Y = np.array([
    [4, 2],
    [6, 2],
    [4, 3]
])

print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

print("\nX × Y:")
print(np.matmul(X, Y))

Shape of X: (3, 3)
Shape of Y: (3, 2)

X × Y:
[[70 30]
 [70 36]
 [56 25]]


A7. Vector Shape and Dimensions

The vector x is created and its shape and number of dimensions are determined using the `shape` and `ndim` attributes. The vector is then reshaped into a matrix with shape (3, 1). The same reshaping operation is performed on y, changing each vector from one dimension to a two-dimensional matrix.

In [35]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("x:", x)
print("Shape of x:", x.shape)
print("Dimensions of x:", x.ndim)

mx = x.reshape(3, 1)

print("\nReshaped x:")
print(mx)
print("Shape:", mx.shape)
print("Dimensions:", mx.ndim)

my = y.reshape(3, 1)

print("\nReshaped y:")
print(my)
print("Shape:", my.shape)
print("Dimensions:", my.ndim)

x: [ 2 -1 -8]
Shape of x: (3,)
Dimensions of x: 1

Reshaped x:
[[ 2]
 [-1]
 [-8]]
Shape: (3, 1)
Dimensions: 2

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Shape: (3, 1)
Dimensions: 2


 A8. Broadcasting

 Broadcasting allows NumPy to perform arithmetic operations between arrays with compatible shapes without manually repeating the smaller array. In this example, a 1-D vector is combined with a 3 × 3 matrix. NumPy automatically applies the vector to each row of the matrix for both subtraction and multiplication.

In [36]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

vector = np.array([1, 2, 3])

print("Matrix:")
print(matrix)

print("\nVector:")
print(vector)

print("\nBroadcasting subtraction:")
print(matrix - vector)

print("\nBroadcasting multiplication:")
print(matrix * vector)

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Vector:
[1 2 3]

Broadcasting subtraction:
[[ 9 18 27]
 [39 48 57]
 [69 78 87]]

Broadcasting multiplication:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


Part B

In this part, two systems of linear equations are represented using matrices. The coefficient matrix and the augmented matrix are used to determine the number of solutions. The matrix rank is compared with the number of variables to determine whether the system has a unique solution, no solution, or infinitely many solutions.

B1. System of Linear Equations

The first system contains two equations and three unknown variables. The coefficient matrix and augmented matrix are created using NumPy. Their ranks are calculated to determine the number of solutions. Since the ranks are equal and less than the number of variables, the system is consistent and has infinitely many solutions. The `linsolve()` function is used to display the solution in parametric form.

In [37]:
import sympy as sp

In [38]:
A1 = np.array([
    [2, 3, -4],
    [1, -4, 0]
], dtype=float)

b1 = np.array([6, 8], dtype=float)

augmented1 = np.column_stack((A1, b1))

print("Coefficient Matrix A:")
print(A1)

print("\nConstants b:")
print(b1)

print("\nRank of A:", np.linalg.matrix_rank(A1))
print("Rank of augmented matrix:",
      np.linalg.matrix_rank(augmented1))

Coefficient Matrix A:
[[ 2.  3. -4.]
 [ 1. -4.  0.]]

Constants b:
[6. 8.]

Rank of A: 2
Rank of augmented matrix: 2


In [39]:
x1, x2, x3 = sp.symbols('x1 x2 x3')

equations1 = [
    sp.Eq(2*x1 + 3*x2 - 4*x3, 6),
    sp.Eq(x1 - 4*x2, 8)
]

solution1 = sp.linsolve(equations1, (x1, x2, x3))

print("Solution:")
print(solution1)

Solution:
{(16*x3/11 + 48/11, 4*x3/11 - 10/11, x3)}


B2. Number of Solutions

The second system also contains two equations and three unknown variables. The ranks of the coefficient matrix and augmented matrix are calculated and compared. Since the ranks are equal and less than the number of variables, the system has infinitely many solutions. The `linsolve()` function is used to find and display the parametric solution.



In [40]:
A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
], dtype=float)

b2 = np.array([10, 8], dtype=float)

augmented2 = np.column_stack((A2, b2))

print("Coefficient Matrix A:")
print(A2)

print("\nConstants b:")
print(b2)

print("\nRank of A:", np.linalg.matrix_rank(A2))
print("Rank of augmented matrix:",
      np.linalg.matrix_rank(augmented2))

Coefficient Matrix A:
[[ 3. -4.  5.]
 [-1.  2. -4.]]

Constants b:
[10.  8.]

Rank of A: 2
Rank of augmented matrix: 2


In [41]:
y1, y2, y3 = sp.symbols('y1 y2 y3')

equations2 = [
    sp.Eq(3*y1 - 4*y2 + 5*y3, 10),
    sp.Eq(-y1 + 2*y2 - 4*y3, 8)
]

solution2 = sp.linsolve(equations2, (y1, y2, y3))

print("Solution:")
print(solution2)

Solution:
{(3*y3 + 26, 7*y3/2 + 17, y3)}
